v0 implementation  with tweet, member api features
f-lab-edu/twitter-clone pull request #4
Opened 2023-04-18 20:56 UTC by insightp25

안녕하세요. 로컬 DB에 프로젝트를 연동해보면서 ERD와 Rest API에 대해 고민하다보니 어느새 기초 기능들을 무작정 구현을 해보게 되었습니다. 혹시 코드의 리뷰나 코멘트를 들을 수 있다면 감사하겠습니다! :)

구현기능 목록:

- 트윗 전체 시간 내림차순으로 불러오기
- 특정 멤버의 트윗 전체 시간 내림차순으로 불러오기
- 트윗 포스팅
- 트윗 삭제
- 회원 등록
- 로그인(이메일만을 활용)
- 로그아웃

- JPA를 잘 알지 못하여 한계가 있지만 적용을 해보았습니다.
- JWT의 경우 JavaScript 기반 타 프레임워크를 통해 구현해본 적이 있지만 Spring에서는 구현해본 적이 없어, 깃헙의 공개 소스코드들을 참고하여 적용하고 활용해 보았습니다.

2023-04-18 21:51 UTC, f-lab-steve requested changes
리뷰를 하다가 이대로 리뷰하기 보다는 먼저 PR을 세부적으로 나눠서 올리는 게 좋을 것 같아 해당 comment부터 남겨드립니다.

아래와 같이 PR을 쪼개어 각 부분이 하나의 PR이 되도록 하면 좋을 것 같습니다.
- JPA설정 부분 (Entity를 만들기 전 상태, DB연결 정보, dependency 설정 등)
- JPA설정을 했으니 설계한 ERD를 토대로 Entity 생성
- 각각의 서비스 구현 PR (Tweet따로, Member따로...)
- 각각의 컨트롤러 구현 PR 
- Spring Security 적용

2023-04-25 18:33 UTC, insightp25 commented
- 지난 커밋을 단계적으로 분리하기위해 커밋을 revert하고분리 후 첫 단계인 MyBatis 및 DB연동 관련 커밋

2023-04-26 03:12 UTC, f-lab-steve approved these changes

2023-04-26 03:12 UTC, f-lab-steve commented on src/test/resources/schema.sql
Hibernate 같은 ORM들은 코드가 곧 Schema가 됩니다. 따라서 코드와 테이블 설계가 같이 git에 의해 버전관리가 되는 셈인데요. myBatis는 해당 기능이 없습니다. 어떤식으로 해결할 수 있을까요?

2023-05-01 16:43 UTC, closed without merging