entity definition - user, follow, tweet, like_tweet
f-lab-edu/twitter-clone pull request #7
Opened 2023-04-27 15:57 UTC by insightp25

## 엔티티
  - user
  - follow
  - tweet
  - like_tweet

## 스키마 버전: ERD_V01.02_E
  - 상세내용(노션): 
    - ERD_V01.02_E: https://messy-side-4ab.notion.site/ERD_V01-02_E-f41e654e831a42ed9316631c89b09e22
  - 지난 PR에서 코드와 table(schema)의 동기화, 버전 관리해 대하여 언급을 주셔서 조사를 하였는데요, 
    - 해결방안으로 flyway와 liquibase 등 툴의 선택지가 있다는 것을 확인하였는데, 해당 툴을 선택해 적용하는 방향이 맞을지 궁금합니다.
    - 당장은 노션에 테이블 버전 정보를 버전별로 문서화하고, 커밋에 해당 테이블 버전을 표기하는 방법을 사용중입니다.

## 중간 변경 사항
  - 스타일 조정: vertical indentations, code convention(snake_case to camel case)
  - createdAt, updatedAt 필드 객체 초기화 코드 변경
  - 엔티티 refence 마이너 업데이트: 스키마 버전 ERD_V1.02_C ->  ERD_V1.02_D
  - getter, setter 삭제
  - @Data 적용
  - 테이블 이름 일부 변경: LIKE -> LIKE_TWEET (사유: like는 MySQL DBMS의 예약어)
  - PK에 대해 기존 auto-increment 제거 -> UUID로 변경. ERD_V1.02_D -> ERD_V1.02_E #19  #20  

## 미정 변경 사항
  - 일부 필드의 @setter에 대해 AccessLevel 불가(NONE) 적용 #21 

## (deprecated)
  - '@Data' 등 lombok을 사용하지 않고 순수 Java로 생성자와 getter와 setter를 정의
    - getter와 setter 모두가 있는 필드와, getter만 있는 필드 구분

2023-04-27 16:25 UTC, f-lab-steve requested changes

2023-04-27 16:25 UTC, f-lab-steve commented on src/main/java/clone/twitter/domain/Follow.java
> +    public Follow(Long follower_id, Long followee_id) {
이런 부분을 조심해야합니다. Style을 맞춰주세요.

2023-04-27 16:25 UTC, f-lab-steve commented on src/main/java/clone/twitter/domain/Follow.java
> +    public Long getFollowerId() {return followerId;}
body가 내용이 없어서 한 줄로 줄이고 싶은 마음이 있겠지만. 스타일을 따르자면 여러줄에 걸쳐서 작성하는게 좋습니다. 많은 IDE들이 code folding (특정 부분을 안보이게 하는 것)을 지원하기 때문에 필요하다면 무시할 수 있거든요.

2023-04-27 16:28 UTC, f-lab-steve commented
* Description 부분에는 리뷰어가 리뷰를 하기 위해 필요한 정보들을 손쉽게 접근할 수 있도록 노력해야합니다. 

예시로는 아래의 부분에 `노션 페이지`를 실제로 링크로 만들어 두면 어떤 문서인지 바로 알고, 빠르게 접근이 가능하겠죠.
```
스키마 버전: ERD_V1.02_C

상세내용을 노션 페이지에 문서화하였습니다.
```

* 롬복을 사용하셔도 괜찮습니다만, 사용하지 이유는 무엇인지 궁금합니다. (꼭 사용해야 한다는 이야기는 아닙니다)

2023-04-27 19:34 UTC, insightp25 commented
> * Description 부분에는 리뷰어가 리뷰를 하기 위해 필요한 정보들을 손쉽게 접근할 수 있도록 노력해야합니다.
> 
> 예시로는 아래의 부분에 `노션 페이지`를 실제로 링크로 만들어 두면 어떤 문서인지 바로 알고, 빠르게 접근이 가능하겠죠.
> 
> ```
> 스키마 버전: ERD_V1.02_C
> 
> 상세내용을 노션 페이지에 문서화하였습니다.
> ```
> 
>  * 롬복을 사용하셔도 괜찮습니다만, 사용하지 이유는 무엇인지 궁금합니다. (꼭 사용해야 한다는 이야기는 아닙니다)

1. 죄송합니다. 노션은 오픈된 공간이라 그랬던 것 같습니다.🥲 다시 생각하니 그게 중요한 게 아닌 것 같아, 뒤늦게라도 아래와 같이 바로 접근하실 수 있는 링크를 공유 드립니다.
  - 스키마 버전 ERD_V1.02_C 노션 링크: https://messy-side-4ab.notion.site/ERD_V01-02_C-a113e04501d54aa88d9b83b3c45f9e55

2. 롬복을 사용하지 않은 이유:
(entity 외에 이후 다른 코드들에서도 lombok을 쓰지 않는다는 의미는 아니었습니다)
- 문제:
  - ```final``` 사용 + ```setter``` 제한: 
    1. DB가 자동생성하는 불변 필드: ```id```, ```createdAt``` 등 없이 객체를 생성하는 경우(유저로부터 특정 필드만 입력받아 DB에 ```save()```할 시)가 있어서 클래스에서 ```final```로 초기화 불가(eg. error: Variable 'id' might not have been initialized) 
    2. ```@Data```어노테이션 사용 시 ```final```이 붙지 않은 모든 필드에 ```setter```와 생성자 자동 지원 기능 사용 강제
- 대안: ```@Data``` 생략 시 트레이드오프를 다시 생각해보았습니다(eg. ```@Data```가 제공하는 ```toString()```, ```equals()``` 등 유용한 기능 포기)
  - 불변 필드를 DB에 update 시도할 시 DB에서 대신 차단(rollback)해줄 것으로 믿고,
    - DB 자동생성 불편 필드에 ```final``` 키워드 포기
    - ```@Data```, ```@AllArgsConstructor``` 사용
이렇게 다시 잠정 결론을 내린 것 같습니다.

2023-04-27 21:22 UTC, insightp25 commented
롬복 개별 애노테이션들이 제공하는 핵심기능 외에 부가기능들에 대해 간과하고 소홀히 생각했었는데, 안을 좀 더 세심히 들여다보게 된 것 같습니다. 
- 애노테이션이 제공하는 유용한 기능들을 모두 직접 재정의할 것이 아니고, 
- 사용하지 않으려고 했던 이유/이슈(```@Data```가 불변 필드에 ```setter``` 자동적용)는 결론적으로 기능상 문제가 없을 것이라고 잠정 결론을 내었고
롬복을 적용한 버전으로 다시 커밋을 하였습니다.😭

2023-04-28 19:46 UTC, f-lab-steve commented
Style오류가 있는 부분은 해결해주시면 좋을 것 같습니다.

Setter가 만들어지는게 걱정이었다면 롬복에서 `@Data`를 사용하더라도 Setter를 만들지 않도록 하는 기능도 있습니다. `AccessLevel`에 대해서 찾아보시면 좋을 것 같습니다.

2023-04-30 06:11 UTC, insightp25 commented
> Style오류가 있는 부분은 해결해주시면 좋을 것 같습니다.
> 
> Setter가 만들어지는게 걱정이었다면 롬복에서 `@Data`를 사용하더라도 Setter를 만들지 않도록 하는 기능도 있습니다. `AccessLevel`에 대해서 찾아보시면 좋을 것 같습니다.

어랏, 이후에 스타일을 조정하여 바로 다시 커밋을 하였습니다! PR의 커밋 이력에는 추가 커밋한 이력이 기록돼있지만, 'file changed' 카테고리 화면의 최상단에는 이전의 커밋이 떠있는 상태입니다. 혹시 추가 커밋상에도 스타일 조정이 필요하다는 말씀이실까요...?🤔 언급 주신다면 다시 확인하겠습니다.🥲

2023-04-30 18:07 UTC, f-lab-steve commented on src/main/java/clone/twitter/domain/Follow.java
> +    public Follow(Long follower_id, Long followee_id) {
여기 snake case는 그대로 있는 것 같습니다.

2023-05-10 16:09 UTC, f-lab-steve approved these changes

2023-05-13 21:01 UTC, merged

2023-06-29 10:19 UTC, insightp25 commented
Can one of the admins verify this patch?